/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.Calendar;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import paneles.CambiaPanel;

/**
 *
 * @author RojeruSan
 */
public class Principal extends javax.swing.JFrame {

    int x, y;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        this.setLocationRelativeTo(this);
        this.uno.setSelected(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
    }
    static boolean maximized = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        uno = new rsbuttom.RSButtonMetro();
        quinto = new rsbuttom.RSButtonMetro();
        dos = new rsbuttom.RSButtonMetro();
        tres = new rsbuttom.RSButtonMetro();
        cuatro = new rsbuttom.RSButtonMetro();
        seis = new rsbuttom.RSButtonMetro();
        ocho = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(1);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(102, 102, 102));

        uno.setBackground(new java.awt.Color(102, 102, 102));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_home_30px.png"))); // NOI18N
        uno.setText("INICIO");
        uno.setColorHover(new java.awt.Color(153, 153, 153));
        uno.setColorNormal(new java.awt.Color(102, 102, 102));
        uno.setColorPressed(new java.awt.Color(102, 102, 102));
        uno.setColorTextPressed(new java.awt.Color(102, 102, 102));
        uno.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        uno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        uno.setIconTextGap(8);
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unoMousePressed(evt);
            }
        });
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        quinto.setBackground(new java.awt.Color(102, 102, 102));
        quinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_calendar_30px_1.png"))); // NOI18N
        quinto.setText("REGISTRO AÑO LECTIVO");
        quinto.setColorHover(new java.awt.Color(153, 153, 153));
        quinto.setColorNormal(new java.awt.Color(102, 102, 102));
        quinto.setColorPressed(new java.awt.Color(102, 102, 102));
        quinto.setColorTextPressed(new java.awt.Color(102, 102, 102));
        quinto.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        quinto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        quinto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        quinto.setIconTextGap(8);
        quinto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quintoMousePressed(evt);
            }
        });
        quinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quintoActionPerformed(evt);
            }
        });

        dos.setBackground(new java.awt.Color(102, 102, 102));
        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_security_lock_30px.png"))); // NOI18N
        dos.setText("R. SEGURIDAD ESTUDIANTE");
        dos.setColorHover(new java.awt.Color(153, 153, 153));
        dos.setColorNormal(new java.awt.Color(102, 102, 102));
        dos.setColorPressed(new java.awt.Color(102, 102, 102));
        dos.setColorTextPressed(new java.awt.Color(102, 102, 102));
        dos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        dos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dos.setIconTextGap(8);
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dosMousePressed(evt);
            }
        });
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setBackground(new java.awt.Color(102, 102, 102));
        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_student_registration_30px.png"))); // NOI18N
        tres.setText("REGISTRO ESTUDIANTE");
        tres.setColorHover(new java.awt.Color(153, 153, 153));
        tres.setColorNormal(new java.awt.Color(102, 102, 102));
        tres.setColorPressed(new java.awt.Color(102, 102, 102));
        tres.setColorTextPressed(new java.awt.Color(102, 102, 102));
        tres.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tres.setIconTextGap(8);
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tresMousePressed(evt);
            }
        });
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        cuatro.setBackground(new java.awt.Color(102, 102, 102));
        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_report_card_30px_1.png"))); // NOI18N
        cuatro.setText("REPORTES");
        cuatro.setColorHover(new java.awt.Color(153, 153, 153));
        cuatro.setColorNormal(new java.awt.Color(102, 102, 102));
        cuatro.setColorPressed(new java.awt.Color(102, 102, 102));
        cuatro.setColorTextPressed(new java.awt.Color(102, 102, 102));
        cuatro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cuatro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cuatro.setIconTextGap(8);
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuatroMousePressed(evt);
            }
        });
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        seis.setBackground(new java.awt.Color(102, 102, 102));
        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_assistive_technology_30px_1.png"))); // NOI18N
        seis.setText("REGISTRO DISCAPACIDADES");
        seis.setColorHover(new java.awt.Color(153, 153, 153));
        seis.setColorNormal(new java.awt.Color(102, 102, 102));
        seis.setColorPressed(new java.awt.Color(102, 102, 102));
        seis.setColorTextPressed(new java.awt.Color(102, 102, 102));
        seis.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        seis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        seis.setIconTextGap(8);
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seisMousePressed(evt);
            }
        });
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(102, 102, 102));
        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soporte_30px.png"))); // NOI18N
        ocho.setText("SOPORTE");
        ocho.setColorHover(new java.awt.Color(153, 153, 153));
        ocho.setColorNormal(new java.awt.Color(102, 102, 102));
        ocho.setColorPressed(new java.awt.Color(102, 102, 102));
        ocho.setColorTextPressed(new java.awt.Color(102, 102, 102));
        ocho.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        ocho.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ocho.setIconTextGap(8);
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ochoMousePressed(evt);
            }
        });
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(quinto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ocho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(quinto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(952, 40));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu30px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        salir.setBackground(new java.awt.Color(102, 102, 102));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salirblanco_30px.png"))); // NOI18N
        salir.setBorder(null);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1331, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentro.setPreferredSize(new java.awt.Dimension(728, 561));
        pnlCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        pnlCentro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1130, 730));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlHome());

        if (this.uno.isSelected()) {
            this.uno.setColorNormal(new Color(153, 153, 153));
            this.uno.setColorHover(new Color(153, 153, 153));
            this.uno.setColorPressed(new Color(153, 153, 153));

            this.dos.setColorNormal(new Color(102, 102, 102));
            this.dos.setColorHover(new Color(102, 102, 102));
            this.dos.setColorPressed(new Color(153, 153, 153));

            this.tres.setColorNormal(new Color(102, 102, 102));
            this.tres.setColorHover(new Color(102, 102, 102));
            this.tres.setColorPressed(new Color(153, 153, 153));

            this.cuatro.setColorNormal(new Color(102, 102, 102));
            this.cuatro.setColorHover(new Color(102, 102, 102));
            this.cuatro.setColorPressed(new Color(153, 153, 153));

            this.quinto.setColorNormal(new Color(102, 102, 102));
            this.quinto.setColorHover(new Color(102, 102, 102));
            this.quinto.setColorPressed(new Color(153, 153, 153));

            this.seis.setColorNormal(new Color(102, 102, 102));
            this.seis.setColorHover(new Color(102, 102, 102));
            this.seis.setColorPressed(new Color(153, 153, 153));
            
            this.ocho.setColorNormal(new Color(102, 102, 102));
            this.ocho.setColorHover(new Color(102, 102, 102));
            this.ocho.setColorPressed(new Color(153, 153, 153));
            

         /////   this.CONFIG.setColorNormal(new Color(102, 102, 102));
        ///    this.CONFIG.setColorHover(new Color(102, 102, 102));
       //     this.CONFIG.setColorPressed(new Color(102, 102, 102));
        } else {
            this.uno.setColorNormal(new Color(102, 102, 102));
            this.uno.setColorHover(new Color(102, 102, 102));
            this.uno.setColorPressed(new Color(153, 153, 153));
        }
        
        System.out.print("\n\nForm Principal T1.1 Cambiar panel ejecutado");
    }//GEN-LAST:event_unoActionPerformed

    private void unoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMousePressed
        this.uno.setSelected(true);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.quinto.setSelected(false);
        this.seis.setSelected(false);
         this.ocho.setSelected(false);
///        this.CONFIG.setSelected(false);

        System.out.print("\n\nForm Principal T1.2 Botón presionado Cambio de panel exitoso");
    }//GEN-LAST:event_unoMousePressed

    private void quintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quintoActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlAño());
        if (this.quinto.isSelected()) {

            this.quinto.setColorNormal(new Color(153, 153, 153));
            this.quinto.setColorHover(new Color(153, 153, 153));
            this.quinto.setColorPressed(new Color(153, 153, 153));

            this.dos.setColorNormal(new Color(102, 102, 102));
            this.dos.setColorHover(new Color(102, 102, 102));
            this.dos.setColorPressed(new Color(153, 153, 153));

            this.tres.setColorNormal(new Color(102, 102, 102));
            this.dos.setColorHover(new Color(102, 102, 102));
            this.dos.setColorPressed(new Color(153, 153, 153));

            this.uno.setColorNormal(new Color(102, 102, 102));
            this.uno.setColorHover(new Color(102, 102, 102));
            this.uno.setColorPressed(new Color(153, 153, 153));

            this.seis.setColorNormal(new Color(102, 102, 102));
            this.seis.setColorHover(new Color(102, 102, 102));
            this.seis.setColorPressed(new Color(153, 153, 153));

            this.cuatro.setColorNormal(new Color(102, 102, 102));
            this.cuatro.setColorHover(new Color(102, 102, 102));
            this.cuatro.setColorPressed(new Color(153, 153, 153));
            
             this.ocho.setColorNormal(new Color(102, 102, 102));
            this.ocho.setColorHover(new Color(102, 102, 102));
            this.ocho.setColorPressed(new Color(153, 153, 153));

       //     this.CONFIG.setColorNormal(new Color(102, 102, 102));
      //      this.CONFIG.setColorHover(new Color(102, 102, 102));
     //      this.CONFIG.setColorPressed(new Color(153, 153, 153));

        } else {
            this.quinto.setColorNormal(new Color(102, 102, 102));
            this.quinto.setColorHover(new Color(102, 102, 102));
            this.quinto.setColorPressed(new Color(153, 153, 153));
        }
        
        System.out.print("\n\nForm Principal T1.3 Botón presionado Cambio de panel exitoso");
    }//GEN-LAST:event_quintoActionPerformed

    private void quintoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quintoMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.quinto.setSelected(true);
        this.seis.setSelected(false);
   //    this.CONFIG.setSelected(false);
          this.ocho.setSelected(false);
    }//GEN-LAST:event_quintoMousePressed

    private void dosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(true);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.quinto.setSelected(false);
        this.seis.setSelected(false);
         this.ocho.setSelected(false);
   //     this.CONFIG.setSelected(false);
    }//GEN-LAST:event_dosMousePressed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlSeguridad());
        if (this.dos.isSelected()) {
            this.dos.setColorNormal(new Color(153, 153, 153));
            this.dos.setColorHover(new Color(153, 153, 153));
            this.dos.setColorPressed(new Color(153, 153, 153));

            this.uno.setColorNormal(new Color(102, 102, 102));
            this.uno.setColorHover(new Color(102, 102, 102));
            this.uno.setColorPressed(new Color(153, 153, 153));

            this.tres.setColorNormal(new Color(102, 102, 102));
            this.tres.setColorHover(new Color(102, 102, 102));
            this.tres.setColorPressed(new Color(153, 153, 153));

            this.seis.setColorNormal(new Color(102, 102, 102));
            this.seis.setColorHover(new Color(102, 102, 102));
            this.seis.setColorPressed(new Color(153, 153, 153));

            this.cuatro.setColorNormal(new Color(102, 102, 102));
            this.cuatro.setColorHover(new Color(102, 102, 102));
            this.cuatro.setColorPressed(new Color(153, 153, 153));

            this.quinto.setColorNormal(new Color(102, 102, 102));
            this.quinto.setColorHover(new Color(102, 102, 102));
            this.quinto.setColorPressed(new Color(153, 153, 153));

       ////     this.CONFIG.setColorNormal(new Color(102, 102, 102));
        ///    this.CONFIG.setColorHover(new Color(102, 102, 102));
        //    this.CONFIG.setColorPressed(new Color(153, 153, 153));
        } else {
            this.dos.setColorNormal(new Color(102, 102, 102));
            this.dos.setColorHover(new Color(102, 102, 102));
            this.dos.setColorPressed(new Color(153, 153, 153));
        }
        
        System.out.print("\n\nForm Principal T1.4 Botón presionado Cambio de panel exitoso");
    }//GEN-LAST:event_dosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = pnlMenu.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
        } else {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        // System.exit(-1);
    }//GEN-LAST:event_salirActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void tresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMousePressed
        // TODO add your handling code here:
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(true);
        this.cuatro.setSelected(false);
        this.quinto.setSelected(false);
         this.seis.setSelected(false);
        
        this.ocho.setSelected(false);
    }//GEN-LAST:event_tresMousePressed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlRegistro());
        if (this.tres.isSelected()) {

            this.tres.setColorNormal(new Color(153, 153, 153));
            this.tres.setColorHover(new Color(153, 153, 153));
            this.tres.setColorPressed(new Color(153, 153, 153));

            this.dos.setColorNormal(new Color(102, 102, 102));
            this.dos.setColorHover(new Color(102, 102, 102));
            this.dos.setColorPressed(new Color(153, 153, 153));

            this.uno.setColorNormal(new Color(102, 102, 102));
            this.uno.setColorHover(new Color(102, 102, 102));
            this.uno.setColorPressed(new Color(153, 153, 153));
            
            this.seis.setColorNormal(new Color(102, 102, 102));
            this.seis.setColorHover(new Color(102, 102, 102));
            this.seis.setColorPressed(new Color(153, 153, 153));
            
            
            this.cuatro.setColorNormal(new Color(102, 102, 102));
            this.cuatro.setColorHover(new Color(102, 102, 102));
            this.cuatro.setColorPressed(new Color(153, 153, 153));

            this.quinto.setColorNormal(new Color(102, 102, 102));
            this.quinto.setColorHover(new Color(102, 102, 102));
            this.quinto.setColorPressed(new Color(153, 153, 153));

      //      this.CONFIG.setColorNormal(new Color(102, 102, 102));
      //      this.CONFIG.setColorHover(new Color(102, 102, 102));
     //       this.CONFIG.setColorPressed(new Color(153, 153, 153));

        } else {
            this.tres.setColorNormal(new Color(102, 102, 102));
            this.tres.setColorHover(new Color(102, 102, 102));
            this.tres.setColorPressed(new Color(153, 153, 153));
        }
        
        System.out.print("\n\nForm Principal T1.5 Botón presionado Cambio de panel exitoso");


    }//GEN-LAST:event_tresActionPerformed

    private void cuatroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMousePressed
        // TODO add your handling code here:this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(true);
        this.quinto.setSelected(false);
         this.seis.setSelected(false);
        
       this.ocho.setSelected(false);

    }//GEN-LAST:event_cuatroMousePressed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlReporte());
        if (this.cuatro.isSelected()) {

            this.cuatro.setColorNormal(new Color(153, 153, 153));
            this.cuatro.setColorHover(new Color(153, 153, 153));
            this.cuatro.setColorPressed(new Color(153, 153, 153));

            this.dos.setColorNormal(new Color(102, 102, 102));
            this.dos.setColorHover(new Color(102, 102, 102));
            this.dos.setColorPressed(new Color(153, 153, 153));
            
            
            this.seis.setColorNormal(new Color(102, 102, 102));
            this.seis.setColorHover(new Color(102, 102, 102));
            this.seis.setColorPressed(new Color(153, 153, 153));
            

            this.tres.setColorNormal(new Color(102, 102, 102));
            this.tres.setColorHover(new Color(102, 102, 102));
            this.tres.setColorPressed(new Color(153, 153, 153));

            this.uno.setColorNormal(new Color(102, 102, 102));
            this.uno.setColorHover(new Color(102, 102, 102));
            this.uno.setColorPressed(new Color(153, 153, 153));

            this.quinto.setColorNormal(new Color(102, 102, 102));
            this.quinto.setColorHover(new Color(102, 102, 102));
            this.quinto.setColorPressed(new Color(153, 153, 153));

        //    this.CONFIG.setColorNormal(new Color(102, 102, 102));
        //    this.CONFIG.setColorHover(new Color(102, 102, 102));
        //    this.CONFIG.setColorPressed(new Color(153, 153, 153));

        } else {
            this.cuatro.setColorNormal(new Color(102, 102, 102));
            this.cuatro.setColorHover(new Color(102, 102, 102));
            this.cuatro.setColorPressed(new Color(153, 153, 153));
        }
        
        System.out.print("\n\nForm Principal T1.6 Botón presionado Cambio de panel exitoso");
    }//GEN-LAST:event_cuatroActionPerformed

    private void seisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMousePressed
        // TODO add your handling code here:
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.quinto.setSelected(false);
         this.seis.setSelected(true);
        
        this.ocho.setSelected(false);
         
    }//GEN-LAST:event_seisMousePressed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
   new CambiaPanel(pnlPrincipal, new paneles.pnlDiscapacidad());
        if (this.seis.isSelected()) {

            this.seis.setColorNormal(new Color(153, 153, 153));
            this.seis.setColorHover(new Color(153, 153, 153));
            this.seis.setColorPressed(new Color(153, 153, 153));

            this.dos.setColorNormal(new Color(102, 102, 102));
            this.dos.setColorHover(new Color(102, 102, 102));
            this.dos.setColorPressed(new Color(153, 153, 153));
            
          
            

            this.tres.setColorNormal(new Color(102, 102, 102));
            this.tres.setColorHover(new Color(102, 102, 102));
            this.tres.setColorPressed(new Color(153, 153, 153));

            this.uno.setColorNormal(new Color(102, 102, 102));
            this.uno.setColorHover(new Color(102, 102, 102));
            this.uno.setColorPressed(new Color(153, 153, 153));

            this.quinto.setColorNormal(new Color(102, 102, 102));
            this.quinto.setColorHover(new Color(102, 102, 102));
            this.quinto.setColorPressed(new Color(153, 153, 153));
 
            this.ocho.setColorNormal(new Color(102, 102, 102));
            this.ocho.setColorHover(new Color(102, 102, 102));
           this.ocho.setColorPressed(new Color(153, 153, 153));

        } else {
            this.seis.setColorNormal(new Color(102, 102, 102));
            this.seis.setColorHover(new Color(102, 102, 102));
            this.seis.setColorPressed(new Color(153, 153, 153));
        }
        
        System.out.print("\n\nForm Principal T1.7 Botón presionado Cambio de panel exitoso");

    }//GEN-LAST:event_seisActionPerformed

    private void ochoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMousePressed
        // TODO add your handling code here:
         new CambiaPanel(pnlPrincipal, new paneles.pnlSoporte());
        if (this.ocho.isSelected()) {

            this.ocho.setColorNormal(new Color(153, 153, 153));
            this.ocho.setColorHover(new Color(153, 153, 153));
            this.ocho.setColorPressed(new Color(153, 153, 153));

            this.dos.setColorNormal(new Color(102, 102, 102));
            this.dos.setColorHover(new Color(102, 102, 102));
            this.dos.setColorPressed(new Color(153, 153, 153));
            
          this.seis.setColorNormal(new Color(102, 102, 102));
            this.seis.setColorHover(new Color(102, 102, 102));
            this.seis.setColorPressed(new Color(153, 153, 153));
            
//            this.CONFIG.setColorNormal(new Color(102, 102, 102));
       ///     this.CONFIG.setColorHover(new Color(102, 102, 102));
      //      this.CONFIG.setColorPressed(new Color(153, 153, 153));

            this.tres.setColorNormal(new Color(102, 102, 102));
            this.tres.setColorHover(new Color(102, 102, 102));
            this.tres.setColorPressed(new Color(153, 153, 153));

            this.uno.setColorNormal(new Color(102, 102, 102));
            this.uno.setColorHover(new Color(102, 102, 102));
            this.uno.setColorPressed(new Color(153, 153, 153));

            this.quinto.setColorNormal(new Color(102, 102, 102));
            this.quinto.setColorHover(new Color(102, 102, 102));
            this.quinto.setColorPressed(new Color(153, 153, 153));

            this.cuatro.setColorNormal(new Color(102, 102, 102));
            this.cuatro.setColorHover(new Color(102, 102, 102));
            this.cuatro.setColorPressed(new Color(153, 153, 153));

        } else {
            this.ocho.setColorNormal(new Color(102, 102, 102));
            this.ocho.setColorHover(new Color(102, 102, 102));
            this.ocho.setColorPressed(new Color(153, 153, 153));
        }
        
        System.out.print("\n\nForm Principal T1.8 Botón presionado Cambio de panel exitoso");
    }//GEN-LAST:event_ochoMousePressed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        // TODO add your handling code here:
            this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.quinto.setSelected(false);
          this.ocho.setSelected(true);
        
         this.seis.setSelected(false);
    }//GEN-LAST:event_ochoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                // try {
                //     UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                new Principal().setVisible(true);
                //  } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                //      Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            //     }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro cuatro;
    private rsbuttom.RSButtonMetro dos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rsbuttom.RSButtonMetro ocho;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private rsbuttom.RSButtonMetro quinto;
    private javax.swing.JButton salir;
    private rsbuttom.RSButtonMetro seis;
    private rsbuttom.RSButtonMetro tres;
    private rsbuttom.RSButtonMetro uno;
    // End of variables declaration//GEN-END:variables
}
