/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Entidades.cls_conexion;
import Entidades.cls_reportes;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author RojeruSan
 */
public class pnlconfig extends javax.swing.JPanel {

   public static int idalectivo;
    
    public pnlconfig() {
        initComponents();
        
       
        
        cls_conexion conec = new cls_conexion();
      conec.cargarCombo("Select concat_WS('-',id,año) as Nombre From añolectivo ",alectivo);
    }
     cls_reportes reportes;
     
    public String CortarCodigo(String Cadena) {

        String res = "";
        for (int i = 0; i <= Cadena.length() - 1; i++) {
            String a = Cadena.substring(i, i + 1);
            if (a.equals("-")) {
                break;
            } else {
                res = res + a;
            }
        }
        return res;
    }
     
   
        
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        alectivo = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(638, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 286, 544, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 25)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Reportes por filtros");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 544, -1));

        alectivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        alectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alectivoActionPerformed(evt);
            }
        });
        add(alectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void alectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alectivoActionPerformed
        
        
        String lolsito = alectivo.getSelectedItem().toString();
        idalectivo = Integer.parseInt(CortarCodigo(lolsito));
        System.err.println("id alectio " + idalectivo);
    }//GEN-LAST:event_alectivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> alectivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
