/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Controladores.MatriculacionJpaController;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import paneles.pnlRegistro;
import static paneles.pnlSeguridad.modelo;



import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RojeruSan
 */
public class pnlConfiguracion extends javax.swing.JPanel {
//Entidades.Matriculacion lol = new Entidades.Matriculacion();
 //Controladores.MatriculacionJpaController matricula = new MatriculacionJpaController();   
 /**
     * Creates new form pnlHome
     */
    public pnlConfiguracion() {
        initComponents();
        
    }
    
    public void comboañolectivo() {
        this.añolectivo.removeAllItems();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemamatriculacioncng", "root", "");
            Statement Sent = con.createStatement();
            ResultSet rs = Sent.executeQuery("select * from añolectivo");
            while (rs.next()) {
                
                this.añolectivo.addItem(rs.getString("año"));
                 
            }
        } catch (Exception e) {

        }
    }

        
     public void Buscar(String valor, String filtro, JTable tablacontactos){

    String [] columnas={"Matricula", "Fecha", "Cédula Estudiante", "Apellidos Estudiante", "Nombres Estudiante ", "Año de basica", "Carnet",
                "Discapacidad", "Porcentaje", "Año Lectivo", "Cedula Representante", "Apellidos Representante", "Nombres Representante", "Direccion", "Telefono Convencional",
                "Telefono Celular ", "Correo", "Codigo Luz"};
    String [] registro=new String[18];
    modelo=new DefaultTableModel(null,columnas); 
    String SSQL;
    Connection conect = null;
 
    if(filtro.equals("2019-2020")){
    
        SSQL= "SELECT n_matricula, fecha, ced_est, ape_est, nom_est, año_bas, carnet,discapacidad,porcentaje,añolectivo,ced_rep,ape_rep,nom_rep,dir_rep,tel_con,tel_celular,correo,codigodeluz  "
              + "FROM contacto WHERE añolectivo LIKE '%"+valor+"%'";
        
    }else if(filtro.equals("2020-2021")){
    
        SSQL= "SELECT id_contacto, nombres, apellidos, email, celular, direccion, ciudad "
              + "FROM matriculacion WHERE email LIKE '%"+valor+"%'";
    
    }
 
     
    

}



    
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Manual = new rsbuttom.RSButtonMetro();
        jLabel38 = new javax.swing.JLabel();
        añolectivo = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 239, 266, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 239, 266, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel17.setText("XXX-XXX-XXX-XXX");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel20.setText("v.1.2.7");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 290, -1));

        Manual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_book_30px.png"))); // NOI18N
        Manual.setText("Manual de Usuario");
        Manual.setColorHover(new java.awt.Color(153, 153, 153));
        Manual.setColorNormal(new java.awt.Color(102, 102, 102));
        Manual.setColorPressed(new java.awt.Color(102, 102, 102));
        Manual.setColorTextPressed(new java.awt.Color(102, 102, 102));
        Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualActionPerformed(evt);
            }
        });
        jPanel1.add(Manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 200, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel38.setText("Seleccionar Año Lectivo Activo:");
        jLabel38.setToolTipText("");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 180, -1));
        jPanel1.add(añolectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 210, -1));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 130, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualActionPerformed

  
       //    Buscar(añolectivo.getSelectedItem());
       
    }//GEN-LAST:event_ManualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro Manual;
    private javax.swing.JComboBox<String> añolectivo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
