/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Entidades.cls_reportes;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author RojeruSan
 */
public class pnlReporte extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlReporte() {
        initComponents();
        combodiscapacidad();
        comboañolectivo();
    }
     cls_reportes reportes;
     
     public void combodiscapacidad() {
        this.dis.removeAllItems();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemamatriculacioncng", "root", "");
            Statement Sent = con.createStatement();
            ResultSet rs = Sent.executeQuery("select * from discapacidad");
            while (rs.next()) {
                this.dis.addItem(rs.getString("tipodediscapacidad"));
            }
        } catch (Exception e) {

        }
    }
     
     public void comboañolectivo() {
        this.añolectivo.removeAllItems();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemamatriculacioncng", "root", "");
            Statement Sent = con.createStatement();
            ResultSet rs = Sent.executeQuery("select * from añolectivo");
            while (rs.next()) {
                
                this.añolectivo.addItem(rs.getString("año"));
                 
            }
        } catch (Exception e) {

        }
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Discapacidadfiltro = new rsbuttom.RSButtonMetro();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Representante = new rsbuttom.RSButtonMetro();
        jLabel9 = new javax.swing.JLabel();
        representante = new rsbuttom.RSButtonMetro();
        añolectivo = new javax.swing.JComboBox<>();
        dis = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Discapacidad = new rsbuttom.RSButtonMetro();
        rep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(638, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingrese la Discapacidad especifica:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 380, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 286, 544, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 25)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Reportes por filtros");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 544, -1));

        Discapacidadfiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_report_card_30px_1.png"))); // NOI18N
        Discapacidadfiltro.setText("Reporte ");
        Discapacidadfiltro.setColorHover(new java.awt.Color(153, 153, 153));
        Discapacidadfiltro.setColorNormal(new java.awt.Color(102, 102, 102));
        Discapacidadfiltro.setColorPressed(new java.awt.Color(102, 102, 102));
        Discapacidadfiltro.setColorTextPressed(new java.awt.Color(102, 102, 102));
        Discapacidadfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscapacidadfiltroActionPerformed(evt);
            }
        });
        add(Discapacidadfiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 25)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Reportes Completos");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 544, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Reporte datos del representante por alumno ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 450, 30));

        Representante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_report_card_30px_1.png"))); // NOI18N
        Representante.setText("Reporte ");
        Representante.setColorHover(new java.awt.Color(153, 153, 153));
        Representante.setColorNormal(new java.awt.Color(102, 102, 102));
        Representante.setColorPressed(new java.awt.Color(102, 102, 102));
        Representante.setColorTextPressed(new java.awt.Color(102, 102, 102));
        Representante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepresentanteActionPerformed(evt);
            }
        });
        add(Representante, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, -1, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ingrese el Año Lectivo:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 330, -1));

        representante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_report_card_30px_1.png"))); // NOI18N
        representante.setText("Reporte ");
        representante.setColorHover(new java.awt.Color(153, 153, 153));
        representante.setColorNormal(new java.awt.Color(102, 102, 102));
        representante.setColorPressed(new java.awt.Color(102, 102, 102));
        representante.setColorTextPressed(new java.awt.Color(102, 102, 102));
        representante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                representanteActionPerformed(evt);
            }
        });
        add(representante, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        añolectivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(añolectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 150, 30));

        dis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 150, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reporte por Discapacidad");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 330, -1));

        Discapacidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_report_card_30px_1.png"))); // NOI18N
        Discapacidad.setText("Reporte ");
        Discapacidad.setColorHover(new java.awt.Color(153, 153, 153));
        Discapacidad.setColorNormal(new java.awt.Color(102, 102, 102));
        Discapacidad.setColorPressed(new java.awt.Color(102, 102, 102));
        Discapacidad.setColorTextPressed(new java.awt.Color(102, 102, 102));
        Discapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscapacidadActionPerformed(evt);
            }
        });
        add(Discapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));
        add(rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 150, 20));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese Cédula del Estudiante");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void DiscapacidadfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscapacidadfiltroActionPerformed
        // TODO add your handling code here:
       String names = "Discapacidadfiltro.jasper";
        String tipo = (dis.getSelectedItem().toString());
        reportes = new cls_reportes();
        reportes.ReporteAport(names, tipo);
    }//GEN-LAST:event_DiscapacidadfiltroActionPerformed

    private void RepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepresentanteActionPerformed
        // TODO add your handling code here:
        String names = "DatosRepresentante.jasper";
        String tipo = (rep.getText());
        reportes = new cls_reportes();
        reportes.ReporteAport(names, tipo);
    }//GEN-LAST:event_RepresentanteActionPerformed

    private void representanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_representanteActionPerformed
        // TODO add your handling code here:
     String names = "AñoLectivo.jasper";
        String tipo = (añolectivo.getSelectedItem().toString());
        reportes = new cls_reportes();
        reportes.ReporteAport(names, tipo);
    }//GEN-LAST:event_representanteActionPerformed

    private void DiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscapacidadActionPerformed
        // TODO add your handling code here:
         String name = "Discapacidad.jasper";
        reportes = new cls_reportes();
        reportes.ReporteCliente(name);
    }//GEN-LAST:event_DiscapacidadActionPerformed

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro Discapacidad;
    private rsbuttom.RSButtonMetro Discapacidadfiltro;
    private rsbuttom.RSButtonMetro Representante;
    private javax.swing.JComboBox<String> añolectivo;
    private javax.swing.JComboBox<String> dis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField rep;
    private rsbuttom.RSButtonMetro representante;
    // End of variables declaration//GEN-END:variables
}
